apiVersion: apps/v1
kind: Deployment
metadata:
  name: aquasafe-frontend
  labels:
    app: aquasafe-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aquasafe-frontend
  template:
    metadata:
      labels:
        app: aquasafe-frontend
    spec:
      containers:
        - name: aquasafe-frontend
          image: veynitha2002/aquasafe:latest
          ports:
            - containerPort: 80
          # Optionally, specify resource requests/limits:
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          # For advanced use cases, you could pass environment variables here if needed at runtime.
