name: Build and Push Docker Image

on:
  push:
    branches: [ "develop" ]

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out repository
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build Docker image
      - name: Build Docker image
        run: |
          docker build \
            --build-arg VITE_BASE_URL=${{ secrets.PROD_BASE_URL }} \
            -t ${{ secrets.DOCKER_USERNAME }}/aquasafe:latest \
            .

      # Step 4: Push Docker image
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/aquasafe:latest
